export interface Country {
  en: string;
  bg: string;
}

// Sorted alphabetically by English name
export const COUNTRIES: Country[] = [
  { en: 'Afghanistan', bg: 'Афганистан' },
  { en: 'Albania', bg: 'Албания' },
  { en: 'Algeria', bg: 'Алжир' },
  { en: 'Andorra', bg: 'Андора' },
  { en: 'Angola', bg: 'Ангола' },
  { en: 'Antigua and Barbuda', bg: 'Антигуа и Барбуда' },
  { en: 'Argentina', bg: 'Аржентина' },
  { en: 'Armenia', bg: 'Армения' },
  { en: 'Australia', bg: 'Австралия' },
  { en: 'Austria', bg: 'Австрия' },
  { en: 'Azerbaijan', bg: 'Азербайджан' },
  { en: 'Bahamas', bg: 'Бахамски острови' },
  { en: 'Bahrain', bg: 'Бахрейн' },
  { en: 'Bangladesh', bg: 'Бангладеш' },
  { en: 'Barbados', bg: 'Барбадос' },
  { en: 'Belarus', bg: 'Беларус' },
  { en: 'Belgium', bg: 'Белгия' },
  { en: 'Belize', bg: 'Белиз' },
  { en: 'Benin', bg: 'Бенин' },
  { en: 'Bhutan', bg: 'Бутан' },
  { en: 'Bolivia', bg: 'Боливия' },
  { en: 'Bosnia and Herzegovina', bg: 'Босна и Херцеговина' },
  { en: 'Botswana', bg: 'Ботсвана' },
  { en: 'Brazil', bg: 'Бразилия' },
  { en: 'Brunei', bg: 'Бруней' },
  { en: 'Bulgaria', bg: 'България' },
  { en: 'Burkina Faso', bg: 'Буркина Фасо' },
  { en: 'Burundi', bg: 'Бурунди' },
  { en: 'Cabo Verde', bg: 'Кабо Верде' },
  { en: 'Cambodia', bg: 'Камбоджа' },
  { en: 'Cameroon', bg: 'Камерун' },
  { en: 'Canada', bg: 'Канада' },
  { en: 'Central African Republic', bg: 'Централноафриканска република' },
  { en: 'Chad', bg: 'Чад' },
  { en: 'Chile', bg: 'Чили' },
  { en: 'China', bg: 'Китай' },
  { en: 'Colombia', bg: 'Колумбия' },
  { en: 'Comoros', bg: 'Коморски острови' },
  { en: 'Congo', bg: 'Конго' },
  { en: 'Costa Rica', bg: 'Коста Рика' },
  { en: 'Croatia', bg: 'Хърватия' },
  { en: 'Cuba', bg: 'Куба' },
  { en: 'Cyprus', bg: 'Кипър' },
  { en: 'Czech Republic', bg: 'Чехия' },
  { en: 'Democratic Republic of the Congo', bg: 'Демократична република Конго' },
  { en: 'Denmark', bg: 'Дания' },
  { en: 'Djibouti', bg: 'Джибути' },
  { en: 'Dominica', bg: 'Доминика' },
  { en: 'Dominican Republic', bg: 'Доминиканска република' },
  { en: 'Ecuador', bg: 'Еквадор' },
  { en: 'Egypt', bg: 'Египет' },
  { en: 'El Salvador', bg: 'Ел Салвадор' },
  { en: 'Equatorial Guinea', bg: 'Екваториална Гвинея' },
  { en: 'Eritrea', bg: 'Еритрея' },
  { en: 'Estonia', bg: 'Естония' },
  { en: 'Eswatini', bg: 'Есватини' },
  { en: 'Ethiopia', bg: 'Етиопия' },
  { en: 'Fiji', bg: 'Фиджи' },
  { en: 'Finland', bg: 'Финландия' },
  { en: 'France', bg: 'Франция' },
  { en: 'Gabon', bg: 'Габон' },
  { en: 'Gambia', bg: 'Гамбия' },
  { en: 'Georgia', bg: 'Грузия' },
  { en: 'Germany', bg: 'Германия' },
  { en: 'Ghana', bg: 'Гана' },
  { en: 'Greece', bg: 'Гърция' },
  { en: 'Grenada', bg: 'Гренада' },
  { en: 'Guatemala', bg: 'Гватемала' },
  { en: 'Guinea', bg: 'Гвинея' },
  { en: 'Guinea-Bissau', bg: 'Гвинея-Бисау' },
  { en: 'Guyana', bg: 'Гвиана' },
  { en: 'Haiti', bg: 'Хаити' },
  { en: 'Honduras', bg: 'Хондурас' },
  { en: 'Hungary', bg: 'Унгария' },
  { en: 'Iceland', bg: 'Исландия' },
  { en: 'India', bg: 'Индия' },
  { en: 'Indonesia', bg: 'Индонезия' },
  { en: 'Iran', bg: 'Иран' },
  { en: 'Iraq', bg: 'Ирак' },
  { en: 'Ireland', bg: 'Ирландия' },
  { en: 'Israel', bg: 'Израел' },
  { en: 'Italy', bg: 'Италия' },
  { en: 'Ivory Coast', bg: 'Кот д\'Ивоар' },
  { en: 'Jamaica', bg: 'Ямайка' },
  { en: 'Japan', bg: 'Япония' },
  { en: 'Jordan', bg: 'Йордания' },
  { en: 'Kazakhstan', bg: 'Казахстан' },
  { en: 'Kenya', bg: 'Кения' },
  { en: 'Kiribati', bg: 'Кирибати' },
  { en: 'Kuwait', bg: 'Кувейт' },
  { en: 'Kyrgyzstan', bg: 'Киргизстан' },
  { en: 'Laos', bg: 'Лаос' },
  { en: 'Latvia', bg: 'Латвия' },
  { en: 'Lebanon', bg: 'Ливан' },
  { en: 'Lesotho', bg: 'Лесото' },
  { en: 'Liberia', bg: 'Либерия' },
  { en: 'Libya', bg: 'Либия' },
  { en: 'Liechtenstein', bg: 'Лихтенщайн' },
  { en: 'Lithuania', bg: 'Литва' },
  { en: 'Luxembourg', bg: 'Люксембург' },
  { en: 'Madagascar', bg: 'Мадагаскар' },
  { en: 'Malawi', bg: 'Малави' },
  { en: 'Malaysia', bg: 'Малайзия' },
  { en: 'Maldives', bg: 'Малдиви' },
  { en: 'Mali', bg: 'Мали' },
  { en: 'Malta', bg: 'Малта' },
  { en: 'Marshall Islands', bg: 'Маршалови острови' },
  { en: 'Mauritania', bg: 'Мавритания' },
  { en: 'Mauritius', bg: 'Мавриций' },
  { en: 'Mexico', bg: 'Мексико' },
  { en: 'Micronesia', bg: 'Микронезия' },
  { en: 'Moldova', bg: 'Молдова' },
  { en: 'Monaco', bg: 'Монако' },
  { en: 'Mongolia', bg: 'Монголия' },
  { en: 'Montenegro', bg: 'Черна гора' },
  { en: 'Morocco', bg: 'Мароко' },
  { en: 'Mozambique', bg: 'Мозамбик' },
  { en: 'Myanmar', bg: 'Мианмар' },
  { en: 'Namibia', bg: 'Намибия' },
  { en: 'Nauru', bg: 'Науру' },
  { en: 'Nepal', bg: 'Непал' },
  { en: 'Netherlands', bg: 'Нидерландия' },
  { en: 'New Zealand', bg: 'Нова Зеландия' },
  { en: 'Nicaragua', bg: 'Никарагуа' },
  { en: 'Niger', bg: 'Нигер' },
  { en: 'Nigeria', bg: 'Нигерия' },
  { en: 'North Korea', bg: 'Северна Корея' },
  { en: 'North Macedonia', bg: 'Северна Македония' },
  { en: 'Norway', bg: 'Норвегия' },
  { en: 'Oman', bg: 'Оман' },
  { en: 'Pakistan', bg: 'Пакистан' },
  { en: 'Palau', bg: 'Палау' },
  { en: 'Panama', bg: 'Панама' },
  { en: 'Papua New Guinea', bg: 'Папуа Нова Гвинея' },
  { en: 'Paraguay', bg: 'Парагвай' },
  { en: 'Peru', bg: 'Перу' },
  { en: 'Philippines', bg: 'Филипини' },
  { en: 'Poland', bg: 'Полша' },
  { en: 'Portugal', bg: 'Португалия' },
  { en: 'Qatar', bg: 'Катар' },
  { en: 'Romania', bg: 'Румъния' },
  { en: 'Russia', bg: 'Русия' },
  { en: 'Rwanda', bg: 'Руанда' },
  { en: 'Saint Kitts and Nevis', bg: 'Сейнт Китс и Невис' },
  { en: 'Saint Lucia', bg: 'Сейнт Лусия' },
  { en: 'Saint Vincent and the Grenadines', bg: 'Сейнт Винсент и Гренадини' },
  { en: 'Samoa', bg: 'Самоа' },
  { en: 'San Marino', bg: 'Сан Марино' },
  { en: 'Sao Tome and Principe', bg: 'Сао Томе и Принсипи' },
  { en: 'Saudi Arabia', bg: 'Саудитска Арабия' },
  { en: 'Senegal', bg: 'Сенегал' },
  { en: 'Serbia', bg: 'Сърбия' },
  { en: 'Seychelles', bg: 'Сейшели' },
  { en: 'Sierra Leone', bg: 'Сиера Леоне' },
  { en: 'Singapore', bg: 'Сингапур' },
  { en: 'Slovakia', bg: 'Словакия' },
  { en: 'Slovenia', bg: 'Словения' },
  { en: 'Solomon Islands', bg: 'Соломонови острови' },
  { en: 'Somalia', bg: 'Сомалия' },
  { en: 'South Africa', bg: 'Южна Африка' },
  { en: 'South Korea', bg: 'Южна Корея' },
  { en: 'South Sudan', bg: 'Южен Судан' },
  { en: 'Spain', bg: 'Испания' },
  { en: 'Sri Lanka', bg: 'Шри Ланка' },
  { en: 'Sudan', bg: 'Судан' },
  { en: 'Suriname', bg: 'Суринам' },
  { en: 'Sweden', bg: 'Швеция' },
  { en: 'Switzerland', bg: 'Швейцария' },
  { en: 'Syria', bg: 'Сирия' },
  { en: 'Taiwan', bg: 'Тайван' },
  { en: 'Tajikistan', bg: 'Таджикистан' },
  { en: 'Tanzania', bg: 'Танзания' },
  { en: 'Thailand', bg: 'Тайланд' },
  { en: 'Timor-Leste', bg: 'Тимор-Лесте' },
  { en: 'Togo', bg: 'Того' },
  { en: 'Tonga', bg: 'Тонга' },
  { en: 'Trinidad and Tobago', bg: 'Тринидад и Тобаго' },
  { en: 'Tunisia', bg: 'Тунис' },
  { en: 'Turkey', bg: 'Турция' },
  { en: 'Turkmenistan', bg: 'Туркменистан' },
  { en: 'Tuvalu', bg: 'Тувалу' },
  { en: 'Uganda', bg: 'Уганда' },
  { en: 'Ukraine', bg: 'Украйна' },
  { en: 'United Arab Emirates', bg: 'Обединени арабски емирства' },
  { en: 'United Kingdom', bg: 'Великобритания' },
  { en: 'United States', bg: 'Съединени щати' },
  { en: 'Uruguay', bg: 'Уругвай' },
  { en: 'Uzbekistan', bg: 'Узбекистан' },
  { en: 'Vanuatu', bg: 'Вануату' },
  { en: 'Vatican City', bg: 'Ватикана' },
  { en: 'Venezuela', bg: 'Венецуела' },
  { en: 'Vietnam', bg: 'Виетнам' },
  { en: 'Yemen', bg: 'Йемен' },
  { en: 'Zambia', bg: 'Замбия' },
  { en: 'Zimbabwe', bg: 'Зимбабве' },
];

/**
 * Localize a stored country name to the active locale.
 * Country names are stored in English (e.g. "Bulgaria"); this maps them to the
 * Bulgarian equivalent when locale === 'bg'. Falls back to the original string
 * if the name isn't a recognised country (so it's safe for free-text fields).
 */
export function localizeCountry(name: string | null | undefined, locale: string): string {
  if (!name) return '';
  const match = COUNTRIES.find((c) => c.en === name || c.bg === name);
  if (!match) return name;
  return locale === 'bg' ? match.bg : match.en;
}
